pipeline:
  build:
    image: golang
    commands:
      - go install
      - go test ./...

  bin:
    image: golang
    commands:
      - ./release.sh
    when:
      event: tag

  publish_release:
    image: plugins/github-release
    api_key:
      from_secret: github_api_key
    files: bin/*
    when:
      event: tag