#please don't touch this
strings:
  residenceTypeHeader: "rodzaj wniosku o legalizację pobytu []"
  residenceTypeTemporary: "pobyt czasowy"
  residenceTypePermanent: "pobyt stały"
  nameSurnameHeader: "nazwisko i imię/ surname and name"
  citizenshipHeader: "OBYWATELSTWO"
  dateOfBirthHeader: "data urodzenia/ Date of birth "
  phoneHeader: "NUMER TELEFONU KONTAKTOWEGO"
  passportHeader: "Seria i numer paszportu"
  residenceCardHeader: "SERIA I NUMER TYTUŁU POBYTOWEGO"
  dataProcessingHeader: "wyrażenie zgody na przetwarzanie danych osobowych []"
  dataProcessingValue: "Wyrażam dobrowolną zgodę na przetwarzanie dotyczących mnie danych osobowych przez Administratora, którym jest Wojewoda Dolnośląski, wykonujący swoje zadania przy pomocy Dolnośląskiego Urzędu Wojewódzkiego we Wrocławiu, zlokalizowanego we Wrocławiu przy pl. Powstańców Warszawy 1, w zakresie: nazwiska, imienia, nr pesel, w celu dokonania rezerwacji wizyty."
  additionalApplicationsHeader: "Dodatkowe wnioski objęte rezerwacją, proszę zaznaczyć właściwe okienko []"
  additionalApplicationTypeChild: "dziecko "
  additionalApplicationTypeSpouse: "żona/mąż     "
  additionalApplicationTypeChildren: "dzieci"
  lpInfo: "sprawy złożone do 1.02.2018 r. o sygnaturze zaczynającej się od LPII są do kierownika Króla, natomiast sprawy po 1.02.2018 do M.Piotrowskiej."
  lpNameSurnameHeader: "nazwisko i imię"
  lpDateOfBirthHeader: "data urodzenia/Date of birth"
  lpPhoneHeader: "NUMER TELEFONU KONTAKTOWEGO"
  lpReferenceNumberHeader: "sygnatura sprawy lub nazwisko inspektora prowadzącego postępowanie"
  lpSubmissionDateHeader: "wpisz datę złożenia wniosku (przesłania drogą pocztową)"

parallelismFactor: 2 #minimum 1
https: false

cities:
  - name: "Jelenia Góra"
    shortName: "JG"
    queue: "102"
    id: "9"
  - name: "Legnica"
    shortName: "LG"
    queue: "95"
    id: "15"
  - name: "Wałbrzych"
    shortName: "WB"
    queue: "96"
    id: "11"
  - name: "Wrocław"
    shortName: "WRO"
    queue: "17"
    id: "1"

departments:
  - name: "Kierownik Oddziału LP I"
    shortName: "LP1"
    queue: "103"
    id: "4"
  - name: "Kierownik Oddziału LP II"
    shortName: "LP2"
    queue: "62"
    id: "6"